# Este fluxo de trabalho usa ações que não são certificadas pelo GitHub.
# Elas são fornecidas por terceiros e são regidas por
# termos de serviço, política de privacidade e suporte
# separados.
# ESLint é uma ferramenta para identificar e relatar padrões
# encontrados em código ECMAScript/JavaScript.
# Mais detalhes em https://github.com/eslint/eslint
# e https://eslint.org

name: ESLint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint
        run: |
          npm install eslint
          npm install @microsoft/eslint-formatter-sarif
          npm install eslint-plugin-import
          npm install globals

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: |
          npx eslint . \
          --ext .js,.jsx,.ts,.tsx \
          --config eslint.config.js \
          --format @microsoft/eslint-formatter-sarif \
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
